version: "3.8"
services:
  simplediscordbot:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace/bot:cached
    env_file:
      - .env
    command: /bin/sh -c "while sleep 1000; do :; done"
